server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /rainbow-bridge/ {
        proxy_pass https://rainbow.me/rainbow-bridge/;
        proxy_ssl_verify off;
        proxy_set_header Host rainbow.me;
        proxy_set_header Referer https://rainbow.me;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
