name: web build deploy
on:
  push:
    branches:
      - zy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout zy 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: add node  🔧
        run: |
          yarn install --ignore-engines
          yarn build
      - name: web deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./dist
          commit_message: auto deploy